minimumReleaseAge: 1440 # https://pnpm.io/supply-chain-security
onlyBuiltDependencies:
  - esbuild
  - sharp
  - unrs-resolver
minimumReleaseAgeExclude:
  - 'next'
  - '@next/env'
  - 'react'
  - 'react-dom'
